apiVersion: v1
kind: Service
metadata:
  name: target-app
  namespace: target
  labels:
    app: target-app
spec:
  selector:
    app: target-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
